### ISSUE TITLE
Database error and page redirect after submit a question

### ISSUE THREAD

**Issue by primantok** [ConnectedCommunities/humhub-modules-questionanswer#32]
Thanks for making this (awesome) module for HumHub (while everything work fine).

I have setup Question & Answer module in space mode. While I submit a question, the user redirected to "global" Q&A page (in my case, the landing page after submit question is domain.com/questionanswer/question/index/). It should be still redirected under "space" not to "global" site (domain.com/s/feedback/questionanswer/question/view?id=1)

When open picked & unanswered tab, I got the following database error:

![picked](https://picoolio.net/images/2016/07/03/qa-picked68d71.png)
![unanswered](https://picoolio.net/images/2016/07/03/qa-unanswerede20dd.png)

HumHub version: 1.1.0-beta.1
Local install via Uniform Server

Thanks

**Comment by benmag** [comment]
Awesome 

Thanks for catching this. I will investigate

**Comment by benmag** [comment]
Looks like HumHub has some migrations in the 1.1.0-beta.1 release. 

This module is designed to be compatible with the latest _stable_ version of HumHub (1.0.1). You are welcome to open a PR with the changes in preparation for 1.1.0's official release. Otherwise the changes will be made a short time after the release.
