### ISSUE TITLE
Menu index, Error yii\db\Exception AND Admin, yii\base\ErrorException

### ISSUE THREAD

**Issue by LokyStaz** [ConnectedCommunities/humhub-modules-questionanswer#38]
When clicking on a link in the menu on the (/space/questionanswer/question/) index page...
I got an Error yii\db\Exception

> Caused by: PDOException
> SQLSTATE[42S22]: Column not found: 1054 Champ 'content.space_id' inconnu dans where clause
> in ...\protected\vendor\yiisoft\yii2\db\Command.php at line 900

```
The SQL being executed was: SELECT q.id, q.post_title, q.post_text, q.post_type, COUNT(DISTINCT answers.id) as answers, (COUNT(DISTINCT up.id) - COUNT(DISTINCT down.id)) as score, (COUNT(DISTINCT up.id) + COUNT(DISTINCT down.id)) as vote_count, COUNT(DISTINCT up.id) as up_votes, COUNT(DISTINCT down.id) as down_votes
FROM content, question_tag qt, question q
LEFT JOIN question_votes up ON (q.id = up.post_id AND up.vote_on = 'question' AND up.vote_type = 'up')
LEFT JOIN question_votes down ON (q.id = down.post_id AND down.vote_on = 'question' AND down.vote_type = 'down')
LEFT JOIN question answers ON (q.id = answers.question_id AND answers.post_type = 'answer')
WHERE q.post_type = 'question'
AND qt.question_id = q.id 
AND qt.tag_id = 5
AND content.object_id = q.id
AND content.object_model LIKE 'humhub\\\\modules\\\\questionanswer\\\\models\\\\Question' AND content.space_id = 2
GROUP BY q.id
ORDER BY score DESC, vote_count DESC, q.created_at DESC
Error Info: Array (
[0] => 42S22
[1] => 1054
[2] => Champ 'content.space_id' inconnu dans where clause
)
```

**Comment by LokyStaz** [comment]
I think all the issues come from that messy url stuff.

for example with Q/A activated in a space: 

The index become : "mydomain/s/test/questionanswer/question/index".
Admin link works. create question works.. (I didn't use the picked stuff)

The link to the unanswered go there: "mydomain/s/test/questionanswer/question/unanswered/" and **make the error**!!

The link to the create question go there: "mydomain/s/test/questionanswer/question/create/"
But questions are created at: "mydomain/questionanswer/question/view?id=1".
The link in the space Q/A index go there: "mydomain/s/test/questionanswer/question/view?id=1" and **work fine**!!

And tags are created at: "mydomain/questionanswer/question/tag?id=1".
The link in the space Q/A index go there: "mydomain/s/test/questionanswer/question/tag?id=1" and **make the error**!!
In same time on the tag page, all link in the top bar go back to the Q/A global link instead of the space where we come from...

To create an answer make trouble aswell cause we are transferred back to "mydomain/questionanswer/question/view?id=1" instead of "mydomain/s/test/questionanswer/question/view?id=1"!
Same for comment creation....

**Comment by LokyStaz** [comment]
So, as an admin I got an error on the question page when there is a comment on an answer !!! No problem with comment on the question.... And a simple members (no admin) don't have this error !!

PHP Notice – yii\base\ErrorException
Array to string conversion

> protected\vendor\yiisoft\yii2\helpers\BaseUrl.php at line 128
> protected\modules\questionanswer\helpers\Url.php at line 48
> protected\modules\questionanswer\views\question\view.php at line 210
> protected\modules\questionanswer\controllers\QuestionController.php at line 151

and some others in protected\vendor\yiisoft\yii2\base.

I confirm that after deleted those comments (only the one on the answer) from the db, everything works fine again !!

**Comment by LokyStaz** [comment]
So this freaking url system make the whole module unusable for space !!!
I got so many "url" errors and it's horrible to theming cause the views are not the same if you use a space container or the base container... I try since a while to correct all that, but it's a huge problem!!!
I think the more easy will be to juste split the module and make one for spaces and one for the base.....

**Comment by benmag** [comment]
I finally got time to look into resolving this 

That first issue you reported seems to be occurring because it was referencing a column in the database that doesn't exist anymore. I believe that's fixed now with my latest change. 

The second issue you reported was the default theme calling the wrong method incorrectly. That should be fixed now.

As for for splitting the module into two, that may well be the best option. The different modes share a lot of the same logic, so keeping them combine is a little easier in some ways and harder in others... I'm also considering just integrating some open source forum software like [Flarum](http://flarum.org/) to speed things along but haven't really looked into the logistics of doing something like that at this stage.

**Comment by benmag** [comment]
I finally got time to look into resolving this 

That first issue you reported seems to be occurring because it was referencing a column in the database that doesn't exist anymore. I believe that's fixed now with my latest change. 

The second issue you reported was the default theme calling the wrong method incorrectly. That should be fixed now.

As for for splitting the module into two, that may well be the best option. The different modes share a lot of the same logic, so keeping them combine is a little easier in some ways and harder in others... I'm also considering just integrating some open source forum software like [Flarum](http://flarum.org/) to speed things along but haven't really looked into the logistics of doing something like that at this stage.
